listening-port=3479
tls-listening-port=5349
min-port=49160
max-port=49200
listening-ip=10.6.0.10
relay-ip=10.6.0.10
external-ip=1.14.58.29/10.6.0.10
realm=screen.flyingrtx.com
server-name=screen.flyingrtx.com

fingerprint
use-auth-secret
stale-nonce=600
total-quota=16
user-quota=4
max-bps=20000000

cert=/certs/fullchain.pem
pkey=/certs/privkey.pem
no-dtls
no-multicast-peers
no-tcp-relay

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=224.0.0.0-255.255.255.255
denied-peer-ip=::1
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff

log-file=stdout
simple-log
